// src/App.tsx
import HelloWorld from "./components/HelloWorld.vue";
// import img from './assets/logo.png';

export default function APP() {
  const img = require("./assets/logo.png"); // eslint-disable-line

  return (
    <div id="app">
      <img src={img} alt="Vue logo" />
      <HelloWorld msg="Welcome to Your Vue.js + TypeScript App" />
    </div>
  );
}

// src/App.vue
<template>
  <img alt="Vue logo" src="./assets/logo.png" />
  <HelloWorld msg="Welcome to Your Vue.js + TypeScript App" />
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue'
import HelloWorld from './components/HelloWorld.vue'

export default defineComponent({
  name: 'App',
  components: {
    HelloWorld,
  },
  props: {
    age: {
      type: Number as PropType<number>,
    },
  },
  setup(props) {
    props.age
    return {}
  },
})
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
